config/routes.rb
Rails.application.routes.draw do
  resources :movies
  resources :clients
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "clients#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/client.rb
class Client < ApplicationRecord
  #cliente pertenece a una pelicula
  belongs_to :movie, dependent: :destroy
end

def to_s
  self.name
end

app/models/movie.rb
class Movie < ApplicationRecord
  #una pelicula tiene muchos clientes
  has_many :clients

  accepts_nested_attributes_for :clients, allow_destroy: true

  def to_s
    self.name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: %i[ show edit update destroy ]
  before_action :set_movies, only: %i[ new edit create destroy update]
#agregar paginación.....

  # GET /clients or /clients.json
  #se agrego la variable @movies
  def index
    @clients = Client.all
    @movies = Movie.all
  end

  # GET /clients/1 or /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients or /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to client_url(@client), notice: "se ha creado nuevo cliente." }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1 or /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to client_url(@client), notice: "Actualizado con exito" }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1 or /clients/1.json
  def destroy
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url, notice: "Se elimino Cliente" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end
    def set_movies
      @movies = Movie.all.pluck :name, :id
    end
    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:name, :age, :movie_id)
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: %i[ show edit update destroy ]
  before_action :set_clients, only: %i[ new edit create destroy update]

  # GET /movies or /movies.json
  #se agrego la variable @clients
  def index
    @movies = Movie.all
    @clients = Client.all
  end

  # GET /movies/1 or /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
    @movie.clients.build
  end

  # GET /movies/1/edit
  def edit
    @movie.clients.build
  end

  # POST /movies or /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to movie_url(@movie), notice: "Se creo nueva pelicula" }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1 or /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to movie_url(@movie), notice: "Se ha actualizado correctamente" }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1 or /movies/1.json
  def destroy
    @movie.destroy

    respond_to do |format|
      format.html { redirect_to movies_url, notice: "Se elimino la pelicula." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    def set_clients
      @clients = Client.all.pluck :name, :id
    end

    # Only allow a list of trusted parameters through.
    def movie_params
      params.require(:movie).permit(:name, clients_attributes: [:id, :name, :age, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/clients/_client.html.erb
<div id="<%= dom_id client %>">
<table class="table table-success table-striped text-center">
<thead>
    <tr>
      <th>ID</th>
      <th>Cliente</th>
      <th>Edad</th>
      <th>Pelicula arrendada</th>
      <th>Accion</th>
      </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= client.id %></td>
      <td><%= client.name %></td>
      <td><%= client.age %></td>
      <td>
      <% if client.movie.nil?%>
        No posee pelicula en arriendo
      <% else %>
        <%= client.movie.name %>
      <% end %>
      </td>
      <td>
        <div class="btn">    
          <%= link_to "Editar", edit_client_path(client), class: "btn btn-warning btn-sm mb-2" %> 
          <%= button_to "Eliminar", client , method: :delete, class: "btn btn-danger btn-sm" %>
        </div>
      </td>
    </tr>
   </tbody>
  </table>

 </div>

app/views/clients/_form.html.erb
<%= form_with(model: client) do |form| %>
  <% if client.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
        <% client.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :Nombre, style: "display: block" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div>
    <%= form.label :Edad, style: "display: block" %>
    <%= form.text_field :age, class: "form-control" %>
  </div>

    <div>
      <%= form.label :Pelicula, style: "display: block" %>
      <%= form.select :movie_id, options_for_select(@movies) %>
    </div>
    <br>
  <div>
    <%= form.submit "Crear", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editar Cliente</h1>
<table class="table table-bordered">
<%= render "form", client: @client %>
</table>

<br>

<div class= "btn btn-primary">
<button class=" btn btn-lg btn-info float-end border-dark"> <%= link_to "mostrar", @client %></button> |
<button class=" btn btn-lg btn-info float-end border-dark"><%= link_to "Regresar a Clientes", clients_path %></button> 
</div>

app/views/clients/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="container">
  <h1>Clientes</h1>
  <p>
    <%= link_to "Nuevo Cliente", new_client_path, class: "btn btn-success btn-sm" %>
  </p>
  <div id="clients">
    <table class="table table-bordered text-center">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Nombre</th>
          <th scope="col">Edad</th>
          <th scope="col">Pelicula arrendada</th>
          <th scope="col">Acción</th>
        </tr>
      </thead>
      <tbody>
        <% @clients.each do |client| %>
          <tr>
            <td scope="col"><%= client.id %></td>
            <td scope="col"><%= client.name %></td>
            <td scope="col"><%= client.age %></td>
            <% if client.movie.nil?%>
            <td scope="col"> No Tiene peliculas arrendadas </td>
            <% else %>
            <td scope="col"><%= client.movie.name %></td>
            <% end %>
            <td>
              <div class="btn-group">
                <%= link_to "Ver cliente", client, class: "btn btn-primary btn-sm" %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/clients/new.html.erb
<h1> Nuevo cliente </h1>

<%= render "form", client: @client %>

<br>

<div>
  <%= link_to "Regresar al index de clientes", clients_path, class: "btn btn-primary btn-l" %>
</div>

app/views/clients/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @client %>

<div>
  <%= link_to "Regresar al index de clientes", clients_path, class: "btn btn-primary btn-l" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlockBuster</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class= "bg-info">
    <%= render "shared/navbar" %>
    <div class="container text-center">
      <%= yield %>
    </div>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_with(model: movie) do |form| %>
  <% if movie.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
        <% movie.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :Nombre, style: "display: block" %>
    <%= form.text_field :name %>
  </div>
    <br>
  <div>
    <%= form.label :Cliente, style: "display: block" %>
    <%= form.select :client_id, options_for_select(@clients) %>
  </div>
    <br>
  <div>
  <%= form.submit "Crear", class: "btn btn-primary border-dark" %>
</div>
<% end %>

app/views/movies/_movie.html.erb
  <div class="col-4 py-2">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title"><%= movie.name %></h5>
        <%= link_to "Ver Pelicula", movie, class: "btn btn-primary" %>
      </div>
    </div>
  </div>

app/views/movies/edit.html.erb
<h1>Editar Pelicula</h1>

<%= render "form", movie: @movie %>

<br>

<div class= "btn-group">
<button class=" btn btn-lg btn-info float-end border-dark me-2"><%= link_to "Mostrar Pelicula", @movie %></button>
<button class=" btn btn-lg btn-info float-end border-dark"><%= link_to "Regresar a Peliculas", movies_path %></button>
</div>

app/views/movies/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="container">
  <h1>Pelicula</h1>
  <%= link_to "Nueva pelicula", new_movie_path, class: "btn btn-warning btn-l mb-2 border-dark"%>
  <div id="movies">
    <div class="row">
      <% @movies.each do |movie| %>
        <%= render movie %>
      <% end %>
    </div>
  </div>
</div>

app/views/movies/new.html.erb
<h1>Nueva Pelicula</h1>

<%= render "form", movie: @movie %>

<br>

<div>
  <%= link_to "Regresar a Peliculas", movies_path, class:" btn btn-lg btn-info  border-dark" %>
</div>

app/views/movies/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @movie %>

<div class=" btn-group">
<button class=" btn btn-lg btn-info border-dark"><%= link_to "Editar", edit_movie_path(@movie) %></button>
<%= button_to "Eliminar pelicula", @movie, method: :delete, class: "btn btn-danger border-dark d-block mx-2 btn-lg" %>
<button class=" btn btn-lg btn-info d-block  border-dark"><%= link_to "Regresar a Peliculas", movies_path %></button>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to 'BlockBuster', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Clientes', clients_path, class: 'nav-link'%>
        </li>
        <li class="nav-item">
          <%= link_to 'Peliculas', movies_path, class: 'nav-link' %>
        </li>
    </div>
  </div>
</nav>